### ISSUE TITLE
down dataset

### ISSUE THREAD

**Issue by dl8207531** [tobybreckon/fire-detection-cnn#22]
the download url "https://durhamuniversity.box.com/s/bxp9bvfcz3anb3lk2f4f3z3rtqyug5b1 " of the dataset you offer, I tried countless times to download it and all failed. Could you offer me other ways to download it, such as google netdriver .etc. Thanks.

**Comment by tobybreckon** [comment]
Re-testing myself, there does appear to be an issue with firefox and this download.

It seems to work well with google chrome (I used - Version 74.0.3729.169 (Official Build) (64-bit)).

I am investigating whether we can now move this to permanent hosting internally to the university, as per the CNN models.

**Comment by tobybreckon** [comment]
OK - we have now moved this to permanent hosting internally to the university instead of via box.com.

A direct download link for the dataset is https://collections.durham.ac.uk/downloads/r2d217qp536. 

A download script ```download-dataset.sh``` is now also provided which will create an additional ```dataset``` directory containing the training dataset (10.5Gb in size, works on Linux/MacOS).

**Comment by dl8207531** [comment]
Thank you very much. I'll have a try
