### ISSUE TITLE
The Tensorflow conversion command doesn't create the same TF model as in the paper

### ISSUE THREAD

**Issue by yurivict** [tobybreckon/fire-detection-cnn#35]
```python firenet-to-protobuf.py``` creates this model instead:
![image](https://user-images.githubusercontent.com/271906/69500725-75b53980-0eb2-11ea-8dde-9d8b865bd308.png)

There are "Const" nodes added, which makes it more complicated and not quite what you probably intended.

**Comment by tobybreckon** [comment]
Interesting, as when I check the model in tensorboard I see this:

![image](https://user-images.githubusercontent.com/3429179/69501682-3cef8180-0eff-11ea-9f7d-2e3e144d92e5.png)

.. which is consistent with the paper. My approach is

- edit line 27 of  ``firenet-to-protobuf.py`` to pass an additional final ``True`` parameter to enable verbosity
```
    convert_to_pb(model, path, input_layer_name,  output_layer_name, pbfilename, True)
``` 
- then run: 
```
tensorboard --logdir="logs"
```

- and visualise it in the browser on ``http://127.0.0.1:6006/#graphs&run=.``

What is your tool chain to visualize ?

I think this is because of the way are visualizing this frozen graph were all variable operations have been replaced by constant operations (using [ https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/graph_util/convert_variables_to_constants]( https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/graph_util/convert_variables_to_constants) in line 76 of ``convertor.py``) as part of the conversion process. This is standard practice in graph freezing as far as I am aware - see line 48 of the example here [https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc](https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adcl). The ``const`` is the diagram are not extra graph nodes, they are present because the graph is frozen for inference AFIAK.

**Comment by yurivict** [comment]
The resulting firenet.pb has constants, switches, etc.
You can open it in Netron and see this for yourself.
These operations are redundant and rather inconvenient for those who just wants to compute.

**Comment by tobybreckon** [comment]
I suspect the _experimental_ support (only) for TensorFlow .pb format from Netron is possibly not displaying the model correctly in this case - I doubt any extra operations or nodes are being actually added during the conversion as there is nowhere in the conversion process where this happens and they are not shown by the TensorFlow visualisation to which the pb net format is native.

This is on the basis that:
- the model is displayed correctly by TensorFlow itself on tensorboard, which is the target framework for the conversion
- the const nodes are in fact not operations in themselves, they are displayed because it is a frozen graph (as part of the freezing process replaces variables with constants) and are in fact labels/monikers on the existing layer operations)
- the conversion follows the standard methodology using the built in TensorFlow, tflearn model routines 
- when you print out the network structure layer by layer in TensorFlow and/or OpenCV none of these additions are present
- under test the operation and performance of the converted model is the same as before conversion

I don't think there is any issue here unless you can visualize this in another tool that fully supports TensorFlow pb format or.TensorFlow itself and get similar results.

**Comment by yurivict** [comment]
Yes, extra nodes are added. I also see them when reading .pb file with my C++ program.

I couldn't figure out how to remove them in TF yet.
