### ISSUE TITLE
Environment problems

### ISSUE THREAD

**Issue by h-peng17** [tobybreckon/fire-detection-cnn#61]
**Describe the issue or your query**
Insert a clear and concise description of what the issue is including any steps to reproduce and/or relevant script output.
I can't run the code. When i run the code 'python firenet.py models/test.mp4', the exceptions occur:
`Loaded CNN network weights ...
Loaded video ...
: cannot connect to X server`

**Computing Environment (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.... LTS ] Linux Ubuntu 18
 - Tensorflow Version:  [e.g. 1.x] 1.15-gpu
 - OpenCV Version: [e.g. 3.4.x] 4.1.2.30
 
 - alternative machine learning environment / toolkit (if applicable): [e.g. keras, pytorch + version]

**Additional context**
Wish for your reply~

**Comment by h-peng17** [comment]
The full log:
![image](https://user-images.githubusercontent.com/39556019/111073395-77789580-8519-11eb-8e80-2c5801ab27eb.png)
![image](https://user-images.githubusercontent.com/39556019/111073415-83fcee00-8519-11eb-9a64-40a0abad90ca.png)

**Comment by tobybreckon** [comment]
This appears to be a generic display permissions problem  with your opencv or X installation rather than one speocic to this repo. Are you running as root in the shell with an X display set for X login user only permissions , perhaps? 

Please try Test 2 from this link - https://github.com/tobybreckon/python-examples-ip/blob/master/TESTING.md - following the preceeding instructions... once that works for you, this will work.
